class StackUnderflowError(Exception):
    pass


class StackOverflowError(Exception):
    pass
